### ISSUE TITLE
League: Implement League > Create League

### ISSUE THREAD

**Issue by tmichalski** [tmichalski/PokerLeague#2]
**How to get to this area....**
1. Login as a new user (remove yourself from the db if necessary)
2. You'll be routed to the Register page
3. The "Create League" is not yet setup

**Tasks**
- [x] Clicking the "Create League" should redirect the user to an Add League page
- [x] Add League page should look similar to Season Add/Edit, but contain the required fields for League (Name, ?)
- [x] Clicking "Save" should send the League to the API and save to the database. 
- [x] Once the save process is done, then redirect the user to the Seasons tab (Seasons List view)

NOTE: There is no place yet to edit the league. Consider adding the league details to the Profile or create a new tab called "League" after Home?

**Comment by harttamale** [comment]
Is this a closed GIT?
